/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputBlockNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputBlockNumber{}

// OutputBlockNumber struct for OutputBlockNumber
type OutputBlockNumber struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// An integer value of the latest block number encoded as decimal
	BlockNumber string `json:"BlockNumber"`
}

type _OutputBlockNumber OutputBlockNumber

// NewOutputBlockNumber instantiates a new OutputBlockNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputBlockNumber(blockNumber string) *OutputBlockNumber {
	this := OutputBlockNumber{}
	this.BlockNumber = blockNumber
	return &this
}

// NewOutputBlockNumberWithDefaults instantiates a new OutputBlockNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputBlockNumberWithDefaults() *OutputBlockNumber {
	this := OutputBlockNumber{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputBlockNumber) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputBlockNumber) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputBlockNumber) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputBlockNumber) SetSchema(v string) {
	o.Schema = &v
}

// GetBlockNumber returns the BlockNumber field value
func (o *OutputBlockNumber) GetBlockNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
func (o *OutputBlockNumber) GetBlockNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockNumber, true
}

// SetBlockNumber sets field value
func (o *OutputBlockNumber) SetBlockNumber(v string) {
	o.BlockNumber = v
}

func (o OutputBlockNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputBlockNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["BlockNumber"] = o.BlockNumber
	return toSerialize, nil
}

func (o *OutputBlockNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"BlockNumber",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputBlockNumber := _OutputBlockNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputBlockNumber)

	if err != nil {
		return err
	}

	*o = OutputBlockNumber(varOutputBlockNumber)

	return err
}

type NullableOutputBlockNumber struct {
	value *OutputBlockNumber
	isSet bool
}

func (v NullableOutputBlockNumber) Get() *OutputBlockNumber {
	return v.value
}

func (v *NullableOutputBlockNumber) Set(val *OutputBlockNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputBlockNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputBlockNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputBlockNumber(val *OutputBlockNumber) *NullableOutputBlockNumber {
	return &NullableOutputBlockNumber{value: val, isSet: true}
}

func (v NullableOutputBlockNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputBlockNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


