/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetFilterLogs type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetFilterLogs{}

// OutputGetFilterLogs struct for OutputGetFilterLogs
type OutputGetFilterLogs struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// An array of log objects, or an empty array if nothing has changed since last poll
	Logs []ResponseLog `json:"Logs"`
}

type _OutputGetFilterLogs OutputGetFilterLogs

// NewOutputGetFilterLogs instantiates a new OutputGetFilterLogs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetFilterLogs(logs []ResponseLog) *OutputGetFilterLogs {
	this := OutputGetFilterLogs{}
	this.Logs = logs
	return &this
}

// NewOutputGetFilterLogsWithDefaults instantiates a new OutputGetFilterLogs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetFilterLogsWithDefaults() *OutputGetFilterLogs {
	this := OutputGetFilterLogs{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetFilterLogs) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetFilterLogs) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetFilterLogs) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetFilterLogs) SetSchema(v string) {
	o.Schema = &v
}

// GetLogs returns the Logs field value
func (o *OutputGetFilterLogs) GetLogs() []ResponseLog {
	if o == nil {
		var ret []ResponseLog
		return ret
	}

	return o.Logs
}

// GetLogsOk returns a tuple with the Logs field value
// and a boolean to check if the value has been set.
func (o *OutputGetFilterLogs) GetLogsOk() ([]ResponseLog, bool) {
	if o == nil {
		return nil, false
	}
	return o.Logs, true
}

// SetLogs sets field value
func (o *OutputGetFilterLogs) SetLogs(v []ResponseLog) {
	o.Logs = v
}

func (o OutputGetFilterLogs) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetFilterLogs) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Logs"] = o.Logs
	return toSerialize, nil
}

func (o *OutputGetFilterLogs) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Logs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetFilterLogs := _OutputGetFilterLogs{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetFilterLogs)

	if err != nil {
		return err
	}

	*o = OutputGetFilterLogs(varOutputGetFilterLogs)

	return err
}

type NullableOutputGetFilterLogs struct {
	value *OutputGetFilterLogs
	isSet bool
}

func (v NullableOutputGetFilterLogs) Get() *OutputGetFilterLogs {
	return v.value
}

func (v *NullableOutputGetFilterLogs) Set(val *OutputGetFilterLogs) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetFilterLogs) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetFilterLogs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetFilterLogs(val *OutputGetFilterLogs) *NullableOutputGetFilterLogs {
	return &NullableOutputGetFilterLogs{value: val, isSet: true}
}

func (v NullableOutputGetFilterLogs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetFilterLogs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


