/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetCode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetCode{}

// OutputGetCode struct for OutputGetCode
type OutputGetCode struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The bytecode from a given address
	Bytecode string `json:"Bytecode"`
}

type _OutputGetCode OutputGetCode

// NewOutputGetCode instantiates a new OutputGetCode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetCode(bytecode string) *OutputGetCode {
	this := OutputGetCode{}
	this.Bytecode = bytecode
	return &this
}

// NewOutputGetCodeWithDefaults instantiates a new OutputGetCode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetCodeWithDefaults() *OutputGetCode {
	this := OutputGetCode{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetCode) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetCode) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetCode) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetCode) SetSchema(v string) {
	o.Schema = &v
}

// GetBytecode returns the Bytecode field value
func (o *OutputGetCode) GetBytecode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Bytecode
}

// GetBytecodeOk returns a tuple with the Bytecode field value
// and a boolean to check if the value has been set.
func (o *OutputGetCode) GetBytecodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bytecode, true
}

// SetBytecode sets field value
func (o *OutputGetCode) SetBytecode(v string) {
	o.Bytecode = v
}

func (o OutputGetCode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetCode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Bytecode"] = o.Bytecode
	return toSerialize, nil
}

func (o *OutputGetCode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Bytecode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetCode := _OutputGetCode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetCode)

	if err != nil {
		return err
	}

	*o = OutputGetCode(varOutputGetCode)

	return err
}

type NullableOutputGetCode struct {
	value *OutputGetCode
	isSet bool
}

func (v NullableOutputGetCode) Get() *OutputGetCode {
	return v.value
}

func (v *NullableOutputGetCode) Set(val *OutputGetCode) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetCode) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetCode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetCode(val *OutputGetCode) *NullableOutputGetCode {
	return &NullableOutputGetCode{value: val, isSet: true}
}

func (v NullableOutputGetCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetCode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


