/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetFilterChanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetFilterChanges{}

// OutputGetFilterChanges struct for OutputGetFilterChanges
type OutputGetFilterChanges struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Result interface{} `json:"Result"`
}

type _OutputGetFilterChanges OutputGetFilterChanges

// NewOutputGetFilterChanges instantiates a new OutputGetFilterChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetFilterChanges(result interface{}) *OutputGetFilterChanges {
	this := OutputGetFilterChanges{}
	this.Result = result
	return &this
}

// NewOutputGetFilterChangesWithDefaults instantiates a new OutputGetFilterChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetFilterChangesWithDefaults() *OutputGetFilterChanges {
	this := OutputGetFilterChanges{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetFilterChanges) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetFilterChanges) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetFilterChanges) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetFilterChanges) SetSchema(v string) {
	o.Schema = &v
}

// GetResult returns the Result field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *OutputGetFilterChanges) GetResult() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *OutputGetFilterChanges) GetResultOk() (*interface{}, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *OutputGetFilterChanges) SetResult(v interface{}) {
	o.Result = v
}

func (o OutputGetFilterChanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetFilterChanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	if o.Result != nil {
		toSerialize["Result"] = o.Result
	}
	return toSerialize, nil
}

func (o *OutputGetFilterChanges) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetFilterChanges := _OutputGetFilterChanges{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetFilterChanges)

	if err != nil {
		return err
	}

	*o = OutputGetFilterChanges(varOutputGetFilterChanges)

	return err
}

type NullableOutputGetFilterChanges struct {
	value *OutputGetFilterChanges
	isSet bool
}

func (v NullableOutputGetFilterChanges) Get() *OutputGetFilterChanges {
	return v.value
}

func (v *NullableOutputGetFilterChanges) Set(val *OutputGetFilterChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetFilterChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetFilterChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetFilterChanges(val *OutputGetFilterChanges) *NullableOutputGetFilterChanges {
	return &NullableOutputGetFilterChanges{value: val, isSet: true}
}

func (v NullableOutputGetFilterChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetFilterChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


