/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetStorageAt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetStorageAt{}

// OutputGetStorageAt struct for OutputGetStorageAt
type OutputGetStorageAt struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The value from a storage position at a given address
	Value string `json:"Value"`
}

type _OutputGetStorageAt OutputGetStorageAt

// NewOutputGetStorageAt instantiates a new OutputGetStorageAt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetStorageAt(value string) *OutputGetStorageAt {
	this := OutputGetStorageAt{}
	this.Value = value
	return &this
}

// NewOutputGetStorageAtWithDefaults instantiates a new OutputGetStorageAt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetStorageAtWithDefaults() *OutputGetStorageAt {
	this := OutputGetStorageAt{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetStorageAt) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetStorageAt) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetStorageAt) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetStorageAt) SetSchema(v string) {
	o.Schema = &v
}

// GetValue returns the Value field value
func (o *OutputGetStorageAt) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *OutputGetStorageAt) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *OutputGetStorageAt) SetValue(v string) {
	o.Value = v
}

func (o OutputGetStorageAt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetStorageAt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Value"] = o.Value
	return toSerialize, nil
}

func (o *OutputGetStorageAt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetStorageAt := _OutputGetStorageAt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetStorageAt)

	if err != nil {
		return err
	}

	*o = OutputGetStorageAt(varOutputGetStorageAt)

	return err
}

type NullableOutputGetStorageAt struct {
	value *OutputGetStorageAt
	isSet bool
}

func (v NullableOutputGetStorageAt) Get() *OutputGetStorageAt {
	return v.value
}

func (v *NullableOutputGetStorageAt) Set(val *OutputGetStorageAt) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetStorageAt) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetStorageAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetStorageAt(val *OutputGetStorageAt) *NullableOutputGetStorageAt {
	return &NullableOutputGetStorageAt{value: val, isSet: true}
}

func (v NullableOutputGetStorageAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetStorageAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


