/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputCall type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputCall{}

// InputCall struct for InputCall
type InputCall struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	BlockNumber string `json:"BlockNumber"`
	// The transaction call object
	Transaction ParamsTransaction `json:"Transaction"`
}

type _InputCall InputCall

// NewInputCall instantiates a new InputCall object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputCall(blockNumber string, transaction ParamsTransaction) *InputCall {
	this := InputCall{}
	this.BlockNumber = blockNumber
	this.Transaction = transaction
	return &this
}

// NewInputCallWithDefaults instantiates a new InputCall object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputCallWithDefaults() *InputCall {
	this := InputCall{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *InputCall) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputCall) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *InputCall) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *InputCall) SetSchema(v string) {
	o.Schema = &v
}

// GetBlockNumber returns the BlockNumber field value
func (o *InputCall) GetBlockNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value
// and a boolean to check if the value has been set.
func (o *InputCall) GetBlockNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockNumber, true
}

// SetBlockNumber sets field value
func (o *InputCall) SetBlockNumber(v string) {
	o.BlockNumber = v
}

// GetTransaction returns the Transaction field value
func (o *InputCall) GetTransaction() ParamsTransaction {
	if o == nil {
		var ret ParamsTransaction
		return ret
	}

	return o.Transaction
}

// GetTransactionOk returns a tuple with the Transaction field value
// and a boolean to check if the value has been set.
func (o *InputCall) GetTransactionOk() (*ParamsTransaction, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Transaction, true
}

// SetTransaction sets field value
func (o *InputCall) SetTransaction(v ParamsTransaction) {
	o.Transaction = v
}

func (o InputCall) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputCall) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["BlockNumber"] = o.BlockNumber
	toSerialize["Transaction"] = o.Transaction
	return toSerialize, nil
}

func (o *InputCall) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"BlockNumber",
		"Transaction",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputCall := _InputCall{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputCall)

	if err != nil {
		return err
	}

	*o = InputCall(varInputCall)

	return err
}

type NullableInputCall struct {
	value *InputCall
	isSet bool
}

func (v NullableInputCall) Get() *InputCall {
	return v.value
}

func (v *NullableInputCall) Set(val *InputCall) {
	v.value = val
	v.isSet = true
}

func (v NullableInputCall) IsSet() bool {
	return v.isSet
}

func (v *NullableInputCall) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputCall(val *InputCall) *NullableInputCall {
	return &NullableInputCall{value: val, isSet: true}
}

func (v NullableInputCall) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputCall) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


