/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputSyncing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputSyncing{}

// OutputSyncing struct for OutputSyncing
type OutputSyncing struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Returns null when the node is fully synchronized, otherwise returns the sync status
	SyncStatus SyncStatus `json:"SyncStatus"`
}

type _OutputSyncing OutputSyncing

// NewOutputSyncing instantiates a new OutputSyncing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputSyncing(syncStatus SyncStatus) *OutputSyncing {
	this := OutputSyncing{}
	this.SyncStatus = syncStatus
	return &this
}

// NewOutputSyncingWithDefaults instantiates a new OutputSyncing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputSyncingWithDefaults() *OutputSyncing {
	this := OutputSyncing{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputSyncing) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputSyncing) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputSyncing) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputSyncing) SetSchema(v string) {
	o.Schema = &v
}

// GetSyncStatus returns the SyncStatus field value
func (o *OutputSyncing) GetSyncStatus() SyncStatus {
	if o == nil {
		var ret SyncStatus
		return ret
	}

	return o.SyncStatus
}

// GetSyncStatusOk returns a tuple with the SyncStatus field value
// and a boolean to check if the value has been set.
func (o *OutputSyncing) GetSyncStatusOk() (*SyncStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SyncStatus, true
}

// SetSyncStatus sets field value
func (o *OutputSyncing) SetSyncStatus(v SyncStatus) {
	o.SyncStatus = v
}

func (o OutputSyncing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputSyncing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["SyncStatus"] = o.SyncStatus
	return toSerialize, nil
}

func (o *OutputSyncing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"SyncStatus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputSyncing := _OutputSyncing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputSyncing)

	if err != nil {
		return err
	}

	*o = OutputSyncing(varOutputSyncing)

	return err
}

type NullableOutputSyncing struct {
	value *OutputSyncing
	isSet bool
}

func (v NullableOutputSyncing) Get() *OutputSyncing {
	return v.value
}

func (v *NullableOutputSyncing) Set(val *OutputSyncing) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputSyncing) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputSyncing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputSyncing(val *OutputSyncing) *NullableOutputSyncing {
	return &NullableOutputSyncing{value: val, isSet: true}
}

func (v NullableOutputSyncing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputSyncing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


