/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputSubscribe type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputSubscribe{}

// OutputSubscribe struct for OutputSubscribe
type OutputSubscribe struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The hex encoded subscription ID. This ID will be attached to all received events and can also be used to cancel the subscription using eth_unsubscribe
	SubscriptionId string `json:"SubscriptionId"`
}

type _OutputSubscribe OutputSubscribe

// NewOutputSubscribe instantiates a new OutputSubscribe object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputSubscribe(subscriptionId string) *OutputSubscribe {
	this := OutputSubscribe{}
	this.SubscriptionId = subscriptionId
	return &this
}

// NewOutputSubscribeWithDefaults instantiates a new OutputSubscribe object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputSubscribeWithDefaults() *OutputSubscribe {
	this := OutputSubscribe{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputSubscribe) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputSubscribe) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputSubscribe) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputSubscribe) SetSchema(v string) {
	o.Schema = &v
}

// GetSubscriptionId returns the SubscriptionId field value
func (o *OutputSubscribe) GetSubscriptionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SubscriptionId
}

// GetSubscriptionIdOk returns a tuple with the SubscriptionId field value
// and a boolean to check if the value has been set.
func (o *OutputSubscribe) GetSubscriptionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SubscriptionId, true
}

// SetSubscriptionId sets field value
func (o *OutputSubscribe) SetSubscriptionId(v string) {
	o.SubscriptionId = v
}

func (o OutputSubscribe) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputSubscribe) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["SubscriptionId"] = o.SubscriptionId
	return toSerialize, nil
}

func (o *OutputSubscribe) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"SubscriptionId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputSubscribe := _OutputSubscribe{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputSubscribe)

	if err != nil {
		return err
	}

	*o = OutputSubscribe(varOutputSubscribe)

	return err
}

type NullableOutputSubscribe struct {
	value *OutputSubscribe
	isSet bool
}

func (v NullableOutputSubscribe) Get() *OutputSubscribe {
	return v.value
}

func (v *NullableOutputSubscribe) Set(val *OutputSubscribe) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputSubscribe) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputSubscribe) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputSubscribe(val *OutputSubscribe) *NullableOutputSubscribe {
	return &NullableOutputSubscribe{value: val, isSet: true}
}

func (v NullableOutputSubscribe) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputSubscribe) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


