/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputNewFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputNewFilter{}

// InputNewFilter struct for InputNewFilter
type InputNewFilter struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	FilterObject FilterObject `json:"FilterObject"`
}

type _InputNewFilter InputNewFilter

// NewInputNewFilter instantiates a new InputNewFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputNewFilter(filterObject FilterObject) *InputNewFilter {
	this := InputNewFilter{}
	this.FilterObject = filterObject
	return &this
}

// NewInputNewFilterWithDefaults instantiates a new InputNewFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputNewFilterWithDefaults() *InputNewFilter {
	this := InputNewFilter{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *InputNewFilter) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputNewFilter) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *InputNewFilter) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *InputNewFilter) SetSchema(v string) {
	o.Schema = &v
}

// GetFilterObject returns the FilterObject field value
func (o *InputNewFilter) GetFilterObject() FilterObject {
	if o == nil {
		var ret FilterObject
		return ret
	}

	return o.FilterObject
}

// GetFilterObjectOk returns a tuple with the FilterObject field value
// and a boolean to check if the value has been set.
func (o *InputNewFilter) GetFilterObjectOk() (*FilterObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterObject, true
}

// SetFilterObject sets field value
func (o *InputNewFilter) SetFilterObject(v FilterObject) {
	o.FilterObject = v
}

func (o InputNewFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputNewFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["FilterObject"] = o.FilterObject
	return toSerialize, nil
}

func (o *InputNewFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"FilterObject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputNewFilter := _InputNewFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputNewFilter)

	if err != nil {
		return err
	}

	*o = InputNewFilter(varInputNewFilter)

	return err
}

type NullableInputNewFilter struct {
	value *InputNewFilter
	isSet bool
}

func (v NullableInputNewFilter) Get() *InputNewFilter {
	return v.value
}

func (v *NullableInputNewFilter) Set(val *InputNewFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableInputNewFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableInputNewFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputNewFilter(val *InputNewFilter) *NullableInputNewFilter {
	return &NullableInputNewFilter{value: val, isSet: true}
}

func (v NullableInputNewFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputNewFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


