/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputGetProof type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputGetProof{}

// InputGetProof struct for InputGetProof
type InputGetProof struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	Address string `json:"Address"`
	BlockNumber *string `json:"BlockNumber,omitempty"`
	// An array of storage-keys that should be proofed and included
	StorageKeys []string `json:"StorageKeys"`
}

type _InputGetProof InputGetProof

// NewInputGetProof instantiates a new InputGetProof object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputGetProof(address string, storageKeys []string) *InputGetProof {
	this := InputGetProof{}
	this.Address = address
	var blockNumber string = "latest"
	this.BlockNumber = &blockNumber
	this.StorageKeys = storageKeys
	return &this
}

// NewInputGetProofWithDefaults instantiates a new InputGetProof object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputGetProofWithDefaults() *InputGetProof {
	this := InputGetProof{}
	var blockNumber string = "latest"
	this.BlockNumber = &blockNumber
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *InputGetProof) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGetProof) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *InputGetProof) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *InputGetProof) SetSchema(v string) {
	o.Schema = &v
}

// GetAddress returns the Address field value
func (o *InputGetProof) GetAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Address
}

// GetAddressOk returns a tuple with the Address field value
// and a boolean to check if the value has been set.
func (o *InputGetProof) GetAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Address, true
}

// SetAddress sets field value
func (o *InputGetProof) SetAddress(v string) {
	o.Address = v
}

// GetBlockNumber returns the BlockNumber field value if set, zero value otherwise.
func (o *InputGetProof) GetBlockNumber() string {
	if o == nil || IsNil(o.BlockNumber) {
		var ret string
		return ret
	}
	return *o.BlockNumber
}

// GetBlockNumberOk returns a tuple with the BlockNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputGetProof) GetBlockNumberOk() (*string, bool) {
	if o == nil || IsNil(o.BlockNumber) {
		return nil, false
	}
	return o.BlockNumber, true
}

// HasBlockNumber returns a boolean if a field has been set.
func (o *InputGetProof) HasBlockNumber() bool {
	if o != nil && !IsNil(o.BlockNumber) {
		return true
	}

	return false
}

// SetBlockNumber gets a reference to the given string and assigns it to the BlockNumber field.
func (o *InputGetProof) SetBlockNumber(v string) {
	o.BlockNumber = &v
}

// GetStorageKeys returns the StorageKeys field value
func (o *InputGetProof) GetStorageKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.StorageKeys
}

// GetStorageKeysOk returns a tuple with the StorageKeys field value
// and a boolean to check if the value has been set.
func (o *InputGetProof) GetStorageKeysOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StorageKeys, true
}

// SetStorageKeys sets field value
func (o *InputGetProof) SetStorageKeys(v []string) {
	o.StorageKeys = v
}

func (o InputGetProof) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputGetProof) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Address"] = o.Address
	if !IsNil(o.BlockNumber) {
		toSerialize["BlockNumber"] = o.BlockNumber
	}
	toSerialize["StorageKeys"] = o.StorageKeys
	return toSerialize, nil
}

func (o *InputGetProof) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Address",
		"StorageKeys",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputGetProof := _InputGetProof{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputGetProof)

	if err != nil {
		return err
	}

	*o = InputGetProof(varInputGetProof)

	return err
}

type NullableInputGetProof struct {
	value *InputGetProof
	isSet bool
}

func (v NullableInputGetProof) Get() *InputGetProof {
	return v.value
}

func (v *NullableInputGetProof) Set(val *InputGetProof) {
	v.value = val
	v.isSet = true
}

func (v NullableInputGetProof) IsSet() bool {
	return v.isSet
}

func (v *NullableInputGetProof) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputGetProof(val *InputGetProof) *NullableInputGetProof {
	return &NullableInputGetProof{value: val, isSet: true}
}

func (v NullableInputGetProof) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputGetProof) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


