/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetBlockReceipts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetBlockReceipts{}

// OutputGetBlockReceipts struct for OutputGetBlockReceipts
type OutputGetBlockReceipts struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// An array of transaction receipt objects
	TransactionReceipts []ResponseTransactionReceipt `json:"TransactionReceipts"`
}

type _OutputGetBlockReceipts OutputGetBlockReceipts

// NewOutputGetBlockReceipts instantiates a new OutputGetBlockReceipts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetBlockReceipts(transactionReceipts []ResponseTransactionReceipt) *OutputGetBlockReceipts {
	this := OutputGetBlockReceipts{}
	this.TransactionReceipts = transactionReceipts
	return &this
}

// NewOutputGetBlockReceiptsWithDefaults instantiates a new OutputGetBlockReceipts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetBlockReceiptsWithDefaults() *OutputGetBlockReceipts {
	this := OutputGetBlockReceipts{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetBlockReceipts) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetBlockReceipts) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetBlockReceipts) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetBlockReceipts) SetSchema(v string) {
	o.Schema = &v
}

// GetTransactionReceipts returns the TransactionReceipts field value
func (o *OutputGetBlockReceipts) GetTransactionReceipts() []ResponseTransactionReceipt {
	if o == nil {
		var ret []ResponseTransactionReceipt
		return ret
	}

	return o.TransactionReceipts
}

// GetTransactionReceiptsOk returns a tuple with the TransactionReceipts field value
// and a boolean to check if the value has been set.
func (o *OutputGetBlockReceipts) GetTransactionReceiptsOk() ([]ResponseTransactionReceipt, bool) {
	if o == nil {
		return nil, false
	}
	return o.TransactionReceipts, true
}

// SetTransactionReceipts sets field value
func (o *OutputGetBlockReceipts) SetTransactionReceipts(v []ResponseTransactionReceipt) {
	o.TransactionReceipts = v
}

func (o OutputGetBlockReceipts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetBlockReceipts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["TransactionReceipts"] = o.TransactionReceipts
	return toSerialize, nil
}

func (o *OutputGetBlockReceipts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TransactionReceipts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetBlockReceipts := _OutputGetBlockReceipts{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetBlockReceipts)

	if err != nil {
		return err
	}

	*o = OutputGetBlockReceipts(varOutputGetBlockReceipts)

	return err
}

type NullableOutputGetBlockReceipts struct {
	value *OutputGetBlockReceipts
	isSet bool
}

func (v NullableOutputGetBlockReceipts) Get() *OutputGetBlockReceipts {
	return v.value
}

func (v *NullableOutputGetBlockReceipts) Set(val *OutputGetBlockReceipts) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetBlockReceipts) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetBlockReceipts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetBlockReceipts(val *OutputGetBlockReceipts) *NullableOutputGetBlockReceipts {
	return &NullableOutputGetBlockReceipts{value: val, isSet: true}
}

func (v NullableOutputGetBlockReceipts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetBlockReceipts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


