/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputAccounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputAccounts{}

// OutputAccounts struct for OutputAccounts
type OutputAccounts struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// An array of addresses owned by the client
	Accounts []string `json:"Accounts"`
}

type _OutputAccounts OutputAccounts

// NewOutputAccounts instantiates a new OutputAccounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputAccounts(accounts []string) *OutputAccounts {
	this := OutputAccounts{}
	this.Accounts = accounts
	return &this
}

// NewOutputAccountsWithDefaults instantiates a new OutputAccounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputAccountsWithDefaults() *OutputAccounts {
	this := OutputAccounts{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputAccounts) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputAccounts) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputAccounts) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputAccounts) SetSchema(v string) {
	o.Schema = &v
}

// GetAccounts returns the Accounts field value
func (o *OutputAccounts) GetAccounts() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *OutputAccounts) GetAccountsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *OutputAccounts) SetAccounts(v []string) {
	o.Accounts = v
}

func (o OutputAccounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputAccounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Accounts"] = o.Accounts
	return toSerialize, nil
}

func (o *OutputAccounts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Accounts",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputAccounts := _OutputAccounts{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputAccounts)

	if err != nil {
		return err
	}

	*o = OutputAccounts(varOutputAccounts)

	return err
}

type NullableOutputAccounts struct {
	value *OutputAccounts
	isSet bool
}

func (v NullableOutputAccounts) Get() *OutputAccounts {
	return v.value
}

func (v *NullableOutputAccounts) Set(val *OutputAccounts) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputAccounts) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputAccounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputAccounts(val *OutputAccounts) *NullableOutputAccounts {
	return &NullableOutputAccounts{value: val, isSet: true}
}

func (v NullableOutputAccounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputAccounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


