/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetUncleCountByBlockNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetUncleCountByBlockNumber{}

// OutputGetUncleCountByBlockNumber struct for OutputGetUncleCountByBlockNumber
type OutputGetUncleCountByBlockNumber struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	UncleCount string `json:"UncleCount"`
}

type _OutputGetUncleCountByBlockNumber OutputGetUncleCountByBlockNumber

// NewOutputGetUncleCountByBlockNumber instantiates a new OutputGetUncleCountByBlockNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetUncleCountByBlockNumber(uncleCount string) *OutputGetUncleCountByBlockNumber {
	this := OutputGetUncleCountByBlockNumber{}
	this.UncleCount = uncleCount
	return &this
}

// NewOutputGetUncleCountByBlockNumberWithDefaults instantiates a new OutputGetUncleCountByBlockNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetUncleCountByBlockNumberWithDefaults() *OutputGetUncleCountByBlockNumber {
	this := OutputGetUncleCountByBlockNumber{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetUncleCountByBlockNumber) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetUncleCountByBlockNumber) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetUncleCountByBlockNumber) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetUncleCountByBlockNumber) SetSchema(v string) {
	o.Schema = &v
}

// GetUncleCount returns the UncleCount field value
func (o *OutputGetUncleCountByBlockNumber) GetUncleCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UncleCount
}

// GetUncleCountOk returns a tuple with the UncleCount field value
// and a boolean to check if the value has been set.
func (o *OutputGetUncleCountByBlockNumber) GetUncleCountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UncleCount, true
}

// SetUncleCount sets field value
func (o *OutputGetUncleCountByBlockNumber) SetUncleCount(v string) {
	o.UncleCount = v
}

func (o OutputGetUncleCountByBlockNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetUncleCountByBlockNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["UncleCount"] = o.UncleCount
	return toSerialize, nil
}

func (o *OutputGetUncleCountByBlockNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"UncleCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetUncleCountByBlockNumber := _OutputGetUncleCountByBlockNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetUncleCountByBlockNumber)

	if err != nil {
		return err
	}

	*o = OutputGetUncleCountByBlockNumber(varOutputGetUncleCountByBlockNumber)

	return err
}

type NullableOutputGetUncleCountByBlockNumber struct {
	value *OutputGetUncleCountByBlockNumber
	isSet bool
}

func (v NullableOutputGetUncleCountByBlockNumber) Get() *OutputGetUncleCountByBlockNumber {
	return v.value
}

func (v *NullableOutputGetUncleCountByBlockNumber) Set(val *OutputGetUncleCountByBlockNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetUncleCountByBlockNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetUncleCountByBlockNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetUncleCountByBlockNumber(val *OutputGetUncleCountByBlockNumber) *NullableOutputGetUncleCountByBlockNumber {
	return &NullableOutputGetUncleCountByBlockNumber{value: val, isSet: true}
}

func (v NullableOutputGetUncleCountByBlockNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetUncleCountByBlockNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


