/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputBlobBaseFee type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputBlobBaseFee{}

// OutputBlobBaseFee struct for OutputBlobBaseFee
type OutputBlobBaseFee struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The expected base fee in wei, represented in decimal format
	BaseFee string `json:"BaseFee"`
}

type _OutputBlobBaseFee OutputBlobBaseFee

// NewOutputBlobBaseFee instantiates a new OutputBlobBaseFee object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputBlobBaseFee(baseFee string) *OutputBlobBaseFee {
	this := OutputBlobBaseFee{}
	this.BaseFee = baseFee
	return &this
}

// NewOutputBlobBaseFeeWithDefaults instantiates a new OutputBlobBaseFee object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputBlobBaseFeeWithDefaults() *OutputBlobBaseFee {
	this := OutputBlobBaseFee{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputBlobBaseFee) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputBlobBaseFee) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputBlobBaseFee) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputBlobBaseFee) SetSchema(v string) {
	o.Schema = &v
}

// GetBaseFee returns the BaseFee field value
func (o *OutputBlobBaseFee) GetBaseFee() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseFee
}

// GetBaseFeeOk returns a tuple with the BaseFee field value
// and a boolean to check if the value has been set.
func (o *OutputBlobBaseFee) GetBaseFeeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BaseFee, true
}

// SetBaseFee sets field value
func (o *OutputBlobBaseFee) SetBaseFee(v string) {
	o.BaseFee = v
}

func (o OutputBlobBaseFee) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputBlobBaseFee) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["BaseFee"] = o.BaseFee
	return toSerialize, nil
}

func (o *OutputBlobBaseFee) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"BaseFee",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputBlobBaseFee := _OutputBlobBaseFee{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputBlobBaseFee)

	if err != nil {
		return err
	}

	*o = OutputBlobBaseFee(varOutputBlobBaseFee)

	return err
}

type NullableOutputBlobBaseFee struct {
	value *OutputBlobBaseFee
	isSet bool
}

func (v NullableOutputBlobBaseFee) Get() *OutputBlobBaseFee {
	return v.value
}

func (v *NullableOutputBlobBaseFee) Set(val *OutputBlobBaseFee) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputBlobBaseFee) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputBlobBaseFee) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputBlobBaseFee(val *OutputBlobBaseFee) *NullableOutputBlobBaseFee {
	return &NullableOutputBlobBaseFee{value: val, isSet: true}
}

func (v NullableOutputBlobBaseFee) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputBlobBaseFee) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


