/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetBlockTransactionCountByNumber type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetBlockTransactionCountByNumber{}

// OutputGetBlockTransactionCountByNumber struct for OutputGetBlockTransactionCountByNumber
type OutputGetBlockTransactionCountByNumber struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The number of transactions associated with a specific block, in decimal value
	TransactionCount string `json:"TransactionCount"`
}

type _OutputGetBlockTransactionCountByNumber OutputGetBlockTransactionCountByNumber

// NewOutputGetBlockTransactionCountByNumber instantiates a new OutputGetBlockTransactionCountByNumber object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetBlockTransactionCountByNumber(transactionCount string) *OutputGetBlockTransactionCountByNumber {
	this := OutputGetBlockTransactionCountByNumber{}
	this.TransactionCount = transactionCount
	return &this
}

// NewOutputGetBlockTransactionCountByNumberWithDefaults instantiates a new OutputGetBlockTransactionCountByNumber object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetBlockTransactionCountByNumberWithDefaults() *OutputGetBlockTransactionCountByNumber {
	this := OutputGetBlockTransactionCountByNumber{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetBlockTransactionCountByNumber) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetBlockTransactionCountByNumber) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetBlockTransactionCountByNumber) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetBlockTransactionCountByNumber) SetSchema(v string) {
	o.Schema = &v
}

// GetTransactionCount returns the TransactionCount field value
func (o *OutputGetBlockTransactionCountByNumber) GetTransactionCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransactionCount
}

// GetTransactionCountOk returns a tuple with the TransactionCount field value
// and a boolean to check if the value has been set.
func (o *OutputGetBlockTransactionCountByNumber) GetTransactionCountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionCount, true
}

// SetTransactionCount sets field value
func (o *OutputGetBlockTransactionCountByNumber) SetTransactionCount(v string) {
	o.TransactionCount = v
}

func (o OutputGetBlockTransactionCountByNumber) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetBlockTransactionCountByNumber) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["TransactionCount"] = o.TransactionCount
	return toSerialize, nil
}

func (o *OutputGetBlockTransactionCountByNumber) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TransactionCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetBlockTransactionCountByNumber := _OutputGetBlockTransactionCountByNumber{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetBlockTransactionCountByNumber)

	if err != nil {
		return err
	}

	*o = OutputGetBlockTransactionCountByNumber(varOutputGetBlockTransactionCountByNumber)

	return err
}

type NullableOutputGetBlockTransactionCountByNumber struct {
	value *OutputGetBlockTransactionCountByNumber
	isSet bool
}

func (v NullableOutputGetBlockTransactionCountByNumber) Get() *OutputGetBlockTransactionCountByNumber {
	return v.value
}

func (v *NullableOutputGetBlockTransactionCountByNumber) Set(val *OutputGetBlockTransactionCountByNumber) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetBlockTransactionCountByNumber) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetBlockTransactionCountByNumber) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetBlockTransactionCountByNumber(val *OutputGetBlockTransactionCountByNumber) *NullableOutputGetBlockTransactionCountByNumber {
	return &NullableOutputGetBlockTransactionCountByNumber{value: val, isSet: true}
}

func (v NullableOutputGetBlockTransactionCountByNumber) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetBlockTransactionCountByNumber) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


