/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SyncStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SyncStatus{}

// SyncStatus struct for SyncStatus
type SyncStatus struct {
	// The current block, same as eth_blockNumber encoded as decimal
	CurrentBlock string `json:"CurrentBlock"`
	// The estimated highest block encoded as decimal
	HighestBlock string `json:"HighestBlock"`
	// The block at which the import started encoded as decimal
	StartingBlock string `json:"StartingBlock"`
}

type _SyncStatus SyncStatus

// NewSyncStatus instantiates a new SyncStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSyncStatus(currentBlock string, highestBlock string, startingBlock string) *SyncStatus {
	this := SyncStatus{}
	this.CurrentBlock = currentBlock
	this.HighestBlock = highestBlock
	this.StartingBlock = startingBlock
	return &this
}

// NewSyncStatusWithDefaults instantiates a new SyncStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSyncStatusWithDefaults() *SyncStatus {
	this := SyncStatus{}
	return &this
}

// GetCurrentBlock returns the CurrentBlock field value
func (o *SyncStatus) GetCurrentBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CurrentBlock
}

// GetCurrentBlockOk returns a tuple with the CurrentBlock field value
// and a boolean to check if the value has been set.
func (o *SyncStatus) GetCurrentBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CurrentBlock, true
}

// SetCurrentBlock sets field value
func (o *SyncStatus) SetCurrentBlock(v string) {
	o.CurrentBlock = v
}

// GetHighestBlock returns the HighestBlock field value
func (o *SyncStatus) GetHighestBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HighestBlock
}

// GetHighestBlockOk returns a tuple with the HighestBlock field value
// and a boolean to check if the value has been set.
func (o *SyncStatus) GetHighestBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HighestBlock, true
}

// SetHighestBlock sets field value
func (o *SyncStatus) SetHighestBlock(v string) {
	o.HighestBlock = v
}

// GetStartingBlock returns the StartingBlock field value
func (o *SyncStatus) GetStartingBlock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StartingBlock
}

// GetStartingBlockOk returns a tuple with the StartingBlock field value
// and a boolean to check if the value has been set.
func (o *SyncStatus) GetStartingBlockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartingBlock, true
}

// SetStartingBlock sets field value
func (o *SyncStatus) SetStartingBlock(v string) {
	o.StartingBlock = v
}

func (o SyncStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SyncStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["CurrentBlock"] = o.CurrentBlock
	toSerialize["HighestBlock"] = o.HighestBlock
	toSerialize["StartingBlock"] = o.StartingBlock
	return toSerialize, nil
}

func (o *SyncStatus) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"CurrentBlock",
		"HighestBlock",
		"StartingBlock",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSyncStatus := _SyncStatus{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSyncStatus)

	if err != nil {
		return err
	}

	*o = SyncStatus(varSyncStatus)

	return err
}

type NullableSyncStatus struct {
	value *SyncStatus
	isSet bool
}

func (v NullableSyncStatus) Get() *SyncStatus {
	return v.value
}

func (v *NullableSyncStatus) Set(val *SyncStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableSyncStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableSyncStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSyncStatus(val *SyncStatus) *NullableSyncStatus {
	return &NullableSyncStatus{value: val, isSet: true}
}

func (v NullableSyncStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSyncStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


