/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InputSendRawTransaction type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InputSendRawTransaction{}

// InputSendRawTransaction struct for InputSendRawTransaction
type InputSendRawTransaction struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The signed transaction (typically signed with a library, using your private key)
	Data string `json:"Data"`
}

type _InputSendRawTransaction InputSendRawTransaction

// NewInputSendRawTransaction instantiates a new InputSendRawTransaction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInputSendRawTransaction(data string) *InputSendRawTransaction {
	this := InputSendRawTransaction{}
	this.Data = data
	return &this
}

// NewInputSendRawTransactionWithDefaults instantiates a new InputSendRawTransaction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInputSendRawTransactionWithDefaults() *InputSendRawTransaction {
	this := InputSendRawTransaction{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *InputSendRawTransaction) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InputSendRawTransaction) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *InputSendRawTransaction) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *InputSendRawTransaction) SetSchema(v string) {
	o.Schema = &v
}

// GetData returns the Data field value
func (o *InputSendRawTransaction) GetData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *InputSendRawTransaction) GetDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *InputSendRawTransaction) SetData(v string) {
	o.Data = v
}

func (o InputSendRawTransaction) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InputSendRawTransaction) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Data"] = o.Data
	return toSerialize, nil
}

func (o *InputSendRawTransaction) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInputSendRawTransaction := _InputSendRawTransaction{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInputSendRawTransaction)

	if err != nil {
		return err
	}

	*o = InputSendRawTransaction(varInputSendRawTransaction)

	return err
}

type NullableInputSendRawTransaction struct {
	value *InputSendRawTransaction
	isSet bool
}

func (v NullableInputSendRawTransaction) Get() *InputSendRawTransaction {
	return v.value
}

func (v *NullableInputSendRawTransaction) Set(val *InputSendRawTransaction) {
	v.value = val
	v.isSet = true
}

func (v NullableInputSendRawTransaction) IsSet() bool {
	return v.isSet
}

func (v *NullableInputSendRawTransaction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInputSendRawTransaction(val *InputSendRawTransaction) *NullableInputSendRawTransaction {
	return &NullableInputSendRawTransaction{value: val, isSet: true}
}

func (v NullableInputSendRawTransaction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInputSendRawTransaction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


