/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputGetTransactionReceipt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputGetTransactionReceipt{}

// OutputGetTransactionReceipt struct for OutputGetTransactionReceipt
type OutputGetTransactionReceipt struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// A transaction receipt object, or null when the transaction is not available
	TransactionReceipt ResponseTransactionReceipt `json:"TransactionReceipt"`
}

type _OutputGetTransactionReceipt OutputGetTransactionReceipt

// NewOutputGetTransactionReceipt instantiates a new OutputGetTransactionReceipt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputGetTransactionReceipt(transactionReceipt ResponseTransactionReceipt) *OutputGetTransactionReceipt {
	this := OutputGetTransactionReceipt{}
	this.TransactionReceipt = transactionReceipt
	return &this
}

// NewOutputGetTransactionReceiptWithDefaults instantiates a new OutputGetTransactionReceipt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputGetTransactionReceiptWithDefaults() *OutputGetTransactionReceipt {
	this := OutputGetTransactionReceipt{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputGetTransactionReceipt) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputGetTransactionReceipt) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputGetTransactionReceipt) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputGetTransactionReceipt) SetSchema(v string) {
	o.Schema = &v
}

// GetTransactionReceipt returns the TransactionReceipt field value
func (o *OutputGetTransactionReceipt) GetTransactionReceipt() ResponseTransactionReceipt {
	if o == nil {
		var ret ResponseTransactionReceipt
		return ret
	}

	return o.TransactionReceipt
}

// GetTransactionReceiptOk returns a tuple with the TransactionReceipt field value
// and a boolean to check if the value has been set.
func (o *OutputGetTransactionReceipt) GetTransactionReceiptOk() (*ResponseTransactionReceipt, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransactionReceipt, true
}

// SetTransactionReceipt sets field value
func (o *OutputGetTransactionReceipt) SetTransactionReceipt(v ResponseTransactionReceipt) {
	o.TransactionReceipt = v
}

func (o OutputGetTransactionReceipt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputGetTransactionReceipt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["TransactionReceipt"] = o.TransactionReceipt
	return toSerialize, nil
}

func (o *OutputGetTransactionReceipt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"TransactionReceipt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputGetTransactionReceipt := _OutputGetTransactionReceipt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputGetTransactionReceipt)

	if err != nil {
		return err
	}

	*o = OutputGetTransactionReceipt(varOutputGetTransactionReceipt)

	return err
}

type NullableOutputGetTransactionReceipt struct {
	value *OutputGetTransactionReceipt
	isSet bool
}

func (v NullableOutputGetTransactionReceipt) Get() *OutputGetTransactionReceipt {
	return v.value
}

func (v *NullableOutputGetTransactionReceipt) Set(val *OutputGetTransactionReceipt) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputGetTransactionReceipt) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputGetTransactionReceipt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputGetTransactionReceipt(val *OutputGetTransactionReceipt) *NullableOutputGetTransactionReceipt {
	return &NullableOutputGetTransactionReceipt{value: val, isSet: true}
}

func (v NullableOutputGetTransactionReceipt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputGetTransactionReceipt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


