/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the QanXlinkValidResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QanXlinkValidResponse{}

// QanXlinkValidResponse struct for QanXlinkValidResponse
type QanXlinkValidResponse struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
}

// NewQanXlinkValidResponse instantiates a new QanXlinkValidResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQanXlinkValidResponse() *QanXlinkValidResponse {
	this := QanXlinkValidResponse{}
	return &this
}

// NewQanXlinkValidResponseWithDefaults instantiates a new QanXlinkValidResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQanXlinkValidResponseWithDefaults() *QanXlinkValidResponse {
	this := QanXlinkValidResponse{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *QanXlinkValidResponse) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *QanXlinkValidResponse) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *QanXlinkValidResponse) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *QanXlinkValidResponse) SetSchema(v string) {
	o.Schema = &v
}

func (o QanXlinkValidResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QanXlinkValidResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	return toSerialize, nil
}

type NullableQanXlinkValidResponse struct {
	value *QanXlinkValidResponse
	isSet bool
}

func (v NullableQanXlinkValidResponse) Get() *QanXlinkValidResponse {
	return v.value
}

func (v *NullableQanXlinkValidResponse) Set(val *QanXlinkValidResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableQanXlinkValidResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableQanXlinkValidResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQanXlinkValidResponse(val *QanXlinkValidResponse) *NullableQanXlinkValidResponse {
	return &NullableQanXlinkValidResponse{value: val, isSet: true}
}

func (v NullableQanXlinkValidResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQanXlinkValidResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


