/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputNewBlockFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputNewBlockFilter{}

// OutputNewBlockFilter struct for OutputNewBlockFilter
type OutputNewBlockFilter struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// A filter id to be used when calling eth_getFilterChanges
	FilterId string `json:"FilterId"`
}

type _OutputNewBlockFilter OutputNewBlockFilter

// NewOutputNewBlockFilter instantiates a new OutputNewBlockFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputNewBlockFilter(filterId string) *OutputNewBlockFilter {
	this := OutputNewBlockFilter{}
	this.FilterId = filterId
	return &this
}

// NewOutputNewBlockFilterWithDefaults instantiates a new OutputNewBlockFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputNewBlockFilterWithDefaults() *OutputNewBlockFilter {
	this := OutputNewBlockFilter{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputNewBlockFilter) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputNewBlockFilter) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputNewBlockFilter) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputNewBlockFilter) SetSchema(v string) {
	o.Schema = &v
}

// GetFilterId returns the FilterId field value
func (o *OutputNewBlockFilter) GetFilterId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FilterId
}

// GetFilterIdOk returns a tuple with the FilterId field value
// and a boolean to check if the value has been set.
func (o *OutputNewBlockFilter) GetFilterIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FilterId, true
}

// SetFilterId sets field value
func (o *OutputNewBlockFilter) SetFilterId(v string) {
	o.FilterId = v
}

func (o OutputNewBlockFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputNewBlockFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["FilterId"] = o.FilterId
	return toSerialize, nil
}

func (o *OutputNewBlockFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"FilterId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputNewBlockFilter := _OutputNewBlockFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputNewBlockFilter)

	if err != nil {
		return err
	}

	*o = OutputNewBlockFilter(varOutputNewBlockFilter)

	return err
}

type NullableOutputNewBlockFilter struct {
	value *OutputNewBlockFilter
	isSet bool
}

func (v NullableOutputNewBlockFilter) Get() *OutputNewBlockFilter {
	return v.value
}

func (v *NullableOutputNewBlockFilter) Set(val *OutputNewBlockFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputNewBlockFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputNewBlockFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputNewBlockFilter(val *OutputNewBlockFilter) *NullableOutputNewBlockFilter {
	return &NullableOutputNewBlockFilter{value: val, isSet: true}
}

func (v NullableOutputNewBlockFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputNewBlockFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


