/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputEstimateGas type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputEstimateGas{}

// OutputEstimateGas struct for OutputEstimateGas
type OutputEstimateGas struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// The estimated amount of gas used
	EstimatedGas string `json:"EstimatedGas"`
}

type _OutputEstimateGas OutputEstimateGas

// NewOutputEstimateGas instantiates a new OutputEstimateGas object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputEstimateGas(estimatedGas string) *OutputEstimateGas {
	this := OutputEstimateGas{}
	this.EstimatedGas = estimatedGas
	return &this
}

// NewOutputEstimateGasWithDefaults instantiates a new OutputEstimateGas object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputEstimateGasWithDefaults() *OutputEstimateGas {
	this := OutputEstimateGas{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputEstimateGas) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputEstimateGas) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputEstimateGas) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputEstimateGas) SetSchema(v string) {
	o.Schema = &v
}

// GetEstimatedGas returns the EstimatedGas field value
func (o *OutputEstimateGas) GetEstimatedGas() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EstimatedGas
}

// GetEstimatedGasOk returns a tuple with the EstimatedGas field value
// and a boolean to check if the value has been set.
func (o *OutputEstimateGas) GetEstimatedGasOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EstimatedGas, true
}

// SetEstimatedGas sets field value
func (o *OutputEstimateGas) SetEstimatedGas(v string) {
	o.EstimatedGas = v
}

func (o OutputEstimateGas) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputEstimateGas) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["EstimatedGas"] = o.EstimatedGas
	return toSerialize, nil
}

func (o *OutputEstimateGas) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"EstimatedGas",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputEstimateGas := _OutputEstimateGas{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputEstimateGas)

	if err != nil {
		return err
	}

	*o = OutputEstimateGas(varOutputEstimateGas)

	return err
}

type NullableOutputEstimateGas struct {
	value *OutputEstimateGas
	isSet bool
}

func (v NullableOutputEstimateGas) Get() *OutputEstimateGas {
	return v.value
}

func (v *NullableOutputEstimateGas) Set(val *OutputEstimateGas) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputEstimateGas) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputEstimateGas) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputEstimateGas(val *OutputEstimateGas) *NullableOutputEstimateGas {
	return &NullableOutputEstimateGas{value: val, isSet: true}
}

func (v NullableOutputEstimateGas) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputEstimateGas) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


