/*
QAN AutoApi

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputUninstallFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputUninstallFilter{}

// OutputUninstallFilter struct for OutputUninstallFilter
type OutputUninstallFilter struct {
	// A URL to the JSON Schema for this object.
	Schema *string `json:"$schema,omitempty"`
	// Returns true if the filter was successfully uninstalled, otherwise false
	Result bool `json:"Result"`
}

type _OutputUninstallFilter OutputUninstallFilter

// NewOutputUninstallFilter instantiates a new OutputUninstallFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputUninstallFilter(result bool) *OutputUninstallFilter {
	this := OutputUninstallFilter{}
	this.Result = result
	return &this
}

// NewOutputUninstallFilterWithDefaults instantiates a new OutputUninstallFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputUninstallFilterWithDefaults() *OutputUninstallFilter {
	this := OutputUninstallFilter{}
	return &this
}

// GetSchema returns the Schema field value if set, zero value otherwise.
func (o *OutputUninstallFilter) GetSchema() string {
	if o == nil || IsNil(o.Schema) {
		var ret string
		return ret
	}
	return *o.Schema
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputUninstallFilter) GetSchemaOk() (*string, bool) {
	if o == nil || IsNil(o.Schema) {
		return nil, false
	}
	return o.Schema, true
}

// HasSchema returns a boolean if a field has been set.
func (o *OutputUninstallFilter) HasSchema() bool {
	if o != nil && !IsNil(o.Schema) {
		return true
	}

	return false
}

// SetSchema gets a reference to the given string and assigns it to the Schema field.
func (o *OutputUninstallFilter) SetSchema(v string) {
	o.Schema = &v
}

// GetResult returns the Result field value
func (o *OutputUninstallFilter) GetResult() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Result
}

// GetResultOk returns a tuple with the Result field value
// and a boolean to check if the value has been set.
func (o *OutputUninstallFilter) GetResultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Result, true
}

// SetResult sets field value
func (o *OutputUninstallFilter) SetResult(v bool) {
	o.Result = v
}

func (o OutputUninstallFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputUninstallFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Schema) {
		toSerialize["$schema"] = o.Schema
	}
	toSerialize["Result"] = o.Result
	return toSerialize, nil
}

func (o *OutputUninstallFilter) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Result",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputUninstallFilter := _OutputUninstallFilter{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputUninstallFilter)

	if err != nil {
		return err
	}

	*o = OutputUninstallFilter(varOutputUninstallFilter)

	return err
}

type NullableOutputUninstallFilter struct {
	value *OutputUninstallFilter
	isSet bool
}

func (v NullableOutputUninstallFilter) Get() *OutputUninstallFilter {
	return v.value
}

func (v *NullableOutputUninstallFilter) Set(val *OutputUninstallFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputUninstallFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputUninstallFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputUninstallFilter(val *OutputUninstallFilter) *NullableOutputUninstallFilter {
	return &NullableOutputUninstallFilter{value: val, isSet: true}
}

func (v NullableOutputUninstallFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputUninstallFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


